module.exports = {
  "usePersistedState": {
    "Persist complex objects": {
      "1": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n</div>",
      "2": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n</div>",
      "3": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "4": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "5": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "6": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "7": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "8": "<div id=\"people\"></div>"
    },
    "Persist complex numbers": {
      "1": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n</div>",
      "2": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n</div>",
      "3": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "4": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "5": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "6": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "7": "<div id=\"people\">\n  <div>\n    <h1>Mehmet Sagir</h1>\n    <p>@onursagir, 1-1-1994</p>\n    <ul>\n      <li>hoeks (1000)</li>\n      <li>@onursagir, @j.doe, @jh.doe</li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johan Doe</h1>\n    <p>@j.doe, 1-1-1994</p>\n    <ul>\n      <li>not-hoeks (0)</li>\n      <li></li>\n    </ul>\n  </div>\n  <div>\n    <h1>Johanna Doe</h1>\n    <p>@jh.doe, 1-1-1994</p>\n    <ul>\n      <li>also-not-hoeks (-1)</li>\n      <li></li>\n    </ul>\n  </div>\n</div>",
      "8": "<div id=\"people\"></div>"
    }
  },
  "__version": "6.3.0"
}
